'use strict';
// Real HTTP/SQLite fixture and Chromium. Does not emulate a Minecraft renderer.
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const { chromium } = require(process.env.TABPREFIX_PLAYWRIGHT_MODULE || 'playwright');
const project = path.resolve(process.argv[2] || '.'), legacy = process.argv.includes('--legacy');
const output = path.join(project, '.build/dream-checks', legacy ? 'legacy' : 'modern');
fs.mkdirSync(output, { recursive: true });
let checks = 0;
const check = (ok, name) => { assert.ok(ok, name); checks++; };
(async () => {
  const provided = fs.readdirSync(path.join(project, '.build/deps/provided')).filter(n => n.endsWith('.jar')).map(n => path.join(project, '.build/deps/provided', n));
  const cp = [path.join(project, '.build/tests.jar'), path.join(project, 'dist/TabPrefix.jar'), ...provided].join(path.delimiter);
  const server = spawn(process.env.TABPREFIX_JAVA || 'java', ['-Xmx384m','-Djava.awt.headless=true', '-Dsun.net.http.allowRestrictedHeaders=true', '-cp', cp, 'me.snowsun.tabprefix.test.DisplayIntegrationTest', project, '--serve', ...(legacy ? ['--legacy'] : [])], { stdio: ['pipe', 'pipe', 'inherit'] });
  let browser;
  try {
    await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('Dream fixture startup timeout')), 20000);
      server.stdout.on('data', data => { if (data.toString().includes('STUDIO_READY')) { clearTimeout(timer); resolve(); } });
      server.once('exit', code => { clearTimeout(timer); reject(new Error('Dream fixture exited: ' + code)); });
    });
    const info = JSON.parse(fs.readFileSync(path.join(project, '.build/studio-test.json'), 'utf8'));
    const token = info.admin.split('#')[1], base = info.admin.split('/studio#')[0];
    browser = await chromium.launch({ headless: true, executablePath: process.env.TABPREFIX_BROWSER_EXECUTABLE || undefined, args: ['--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu'] });
    const context = await browser.newContext({ viewport: { width: 1600, height: 1100 } }), page = await context.newPage(), errors = [];
    page.on('pageerror', e => errors.push(e.message)); page.on('dialog', d => d.accept());
    const headers = { Authorization: 'Bearer ' + token };
    const api = async (route, data, extra = {}) => {
      const response = data === undefined ? await context.request.get(base + '/api/' + route, { headers: { ...headers, ...extra } }) : await context.request.post(base + '/api/' + route, { headers: { ...headers, ...extra }, data });
      return { code: response.status(), data: await response.json() };
    };
    const state = () => page.evaluate(() => window.TabPrefixStudio.state.design);
    const success = () => page.waitForFunction(() => document.querySelector('#notice').classList.contains('success'));
    await page.goto(info.admin);
    await page.waitForFunction(() => document.querySelector('#owner').textContent === 'SnowySun' && document.querySelector('#session-state').textContent === 'Connected');
    check(await page.locator('.nav svg').count() === 9, 'Consistent SVG navigation');
    const session = (await api('session')).data;
    check(session.legacyFont === legacy && session.imagesEnabled, 'Server advertises the actual font capability');
    check(await page.locator('#workbench-theme svg').count()===1 && await page.locator('#workbench-search svg').count()===1,'Shared theme and search controls use SVG icons');
    await page.locator('#workbench-theme').click();check(await page.evaluate(()=>document.documentElement.dataset.theme)==='light','Studio switches to light theme');
    await page.keyboard.press('Control+k');await page.locator('#workbench-query').fill('Screen');await page.locator('#workbench-query').press('Enter');
    check(await page.locator('#panel-hud').isVisible() && !await page.locator('#workbench-command').isVisible(),'Command palette navigates with the keyboard');
    await page.locator('[data-panel="dream"]').click();
    check(await page.locator('#page-title').textContent() === 'Your TAB starts with an idea.', 'Dream panel title');
    check(await page.locator('[data-dream-index]').count() === 80, 'Four columns and 80 cells');
    await page.locator('#language').click();
    check(await page.locator('#page-title').textContent() === 'Ваш TAB начинается с идеи.', 'New panels switch to Russian');
    await page.locator('#language').click();
    check(await page.locator('#dream-palette .element-tile').evaluateAll(nodes => nodes.every(n => { const a = n.getBoundingClientRect(), b = n.closest('.card').getBoundingClientRect(); return a.left >= b.left && a.right <= b.right; })), 'Palette tiles stay inside the desktop card');
    await page.screenshot({path:path.join(output,'dream-light.png'),fullPage:true});await page.locator('#workbench-theme').click();
    check(await page.locator('#dream-palette .tile-icon svg').count()===10,'Palette uses individual vector icons');
    await page.locator('#dream-clear').click();
    await page.locator('#dream-palette [data-element="TEXT"]').dragTo(page.locator('[data-dream-index="0"]'));
    check((await state()).slots[0].kind === 'TEXT' && (await state()).layoutEnabled, 'Palette native drag adds a block');
    await page.locator('#block-text').fill('<gold>DREAM TAB</gold>');
    await page.locator('[data-dream-index="0"]').dragTo(page.locator('[data-dream-index="1"]'));
    check((await state()).slots[1].line.text.includes('DREAM TAB') && (await state()).slots[0].kind === 'EMPTY', 'Native cell drag swaps content');
    await page.locator('#undo').click(); check((await state()).slots[0].line.text.includes('DREAM TAB'), 'Dream drag is undoable');
    await page.locator('#redo').click(); check((await state()).slots[1].line.text.includes('DREAM TAB'), 'Dream drag is redoable');
    await page.locator('#dream-palette [data-element="PLAYERS"]').dragTo(page.locator('[data-dream-index="20"]'));
    const filled = (await state()).slots.slice(20, 40);
    check(filled.every(s => s.kind === 'PLAYER') && new Set(filled.map(s => s.playerIndex)).size === 20, 'Player list fills a column with unique positions');
    const headerBefore = (await state()).header.length;
    await page.locator('#dream-palette [data-element="ONLINE"]').dragTo(page.locator('#dream-header'));
    check((await state()).header.length === headerBefore + 1 && (await state()).headerEnabled, 'Palette adds a header line');
    await page.locator('#apply').click(); await success();
    let saved = (await api('display/design')).data.design;
    check(saved.slots[1].line.text.includes('DREAM TAB') && saved.slots[20].kind === 'PLAYER', 'Dream layout persists through the real API');
    await page.screenshot({ path: path.join(output, 'dream-desktop.png'), fullPage: true });
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Dream desktop has no page overflow');
    await page.locator('[data-panel="hud"]').click();
    await page.locator('#hud-palette [data-element="HEALTH"]').dragTo(page.locator('[data-hud-anchor="ACTION_BAR"]'));
    check((await state()).screenEnabled && (await state()).screen[0].anchor === 'ACTION_BAR', 'HUD palette uses a real client anchor');
    await page.waitForFunction(() => document.querySelector('#screen-action').textContent.includes('20/20'));
    check(await page.locator('#screen-action').textContent().then(x => !x.includes('{health}')), 'HUD preview resolves player data on the server');
    await page.locator('#screen-animation').selectOption('FRAMES');
    await page.locator('#screen-frames').fill('<green>ONE</green>\n<gold>TWO</gold>');
    await page.locator('#screen-speed').fill('0.2'); await page.locator('#screen-speed').press('Tab');
    check((await state()).screen[0].line.frames.length === 2 && (await state()).screen[0].line.speed === 4, 'HUD frame editor splits real lines and converts seconds');
    await page.locator('#screen-animation').selectOption('NONE');
    await page.locator('#screen-worlds').fill('nether');
    await page.waitForFunction(() => window.TabPrefixStudio.state.preview?.screenElements?.[0]?.reason === 'WORLD');
    check(await page.locator('#screen-action').textContent() === '', 'HUD preview honors world filters');
    await page.locator('#screen-worlds').fill('world');
    await page.waitForFunction(() => document.querySelector('#screen-action').textContent.includes('20/20'));
    await page.locator('.screen-element').first().dragTo(page.locator('[data-hud-anchor="TITLE"]'));
    check((await state()).screen[0].anchor === 'TITLE', 'Existing HUD block moves between client anchors');
    await page.locator('#screen-element-enabled').uncheck();
    await page.waitForFunction(() => document.querySelector('#screen-title').textContent === '');
    check(!(await state()).screen[0].enabled, 'Each HUD block can be disabled');
    await page.locator('#screen-element-enabled').check();
    await page.locator('#apply').click(); await success();
    saved = (await api('display/design')).data.design;
    check(saved.screen[0].line.frames.length === 2 && saved.screen[0].worlds[0] === 'world', 'HUD settings persist');
    await page.screenshot({ path: path.join(output, 'hud-desktop.png'), fullPage: true });
    await page.locator('[data-panel="glyphs"]').click();
    await page.locator('#pixel-draw-symbol').click();
    check(await page.locator('#pixel-canvas').evaluate(c => Array.from(c.getContext('2d').getImageData(0, 0, 16, 16).data).some((v, i) => i % 4 === 3 && v > 0)), 'Pixel editor creates real PNG pixels');
    await page.locator('#pixel-save').click();
    await page.waitForFunction(() => document.querySelectorAll('#glyph-images [data-image]').length === 1);
    const asset = (await api('display/assets')).data[0];
    check(asset.id && asset.glyph.charCodeAt(0) >= 0xe000, 'Created image gets a permanent private-use code');
    const assetResponse = await context.request.get(base + '/api/display/asset/' + asset.id, { headers });
    check(assetResponse.status() === 200 && assetResponse.headers()['content-type'].includes('image/png'), 'Authenticated thumbnail returns a real PNG');
    const noAuth = await context.request.get(base + '/api/display/asset/' + asset.id);
    check(noAuth.status() === 401, 'Image catalog requires authentication');
    const playerHeaders = { Authorization: 'Bearer ' + info.player.split('#')[1] };
    check((await context.request.get(base + '/api/display/assets', { headers: playerHeaders })).status() === 403, 'Personal-settings session cannot read the image catalog');
    check((await context.request.post(base + '/api/display/image', { headers: playerHeaders, data: await assetResponse.body() })).status() === 403, 'Personal-settings session cannot create images');
    check((await api('display/pack/rebuild', {}, { Origin: 'https://untrusted.invalid' })).code === 403, 'Pack mutations reject foreign Origin');
    check((await api('display/font-baseline', Buffer.alloc(3), { 'Content-Type': 'application/octet-stream' })).code === 400, 'Invalid original font length rejected');
    const invalid = JSON.parse(JSON.stringify(saved)); invalid.screen[0].anchor = 'UNSUPPORTED';
    check((await api('display/design', { design: invalid, revision: (await api('display/design')).data.revision })).code === 400, 'API rejects unsupported screen anchors');
    if (legacy) {
      await page.locator('#font-baseline').setInputFiles({ name: 'glyph_sizes.bin', mimeType: 'application/octet-stream', buffer: Buffer.alloc(65536) });
      await page.waitForFunction(() => document.querySelector('#notice').classList.contains('success'));
      check((await api('display/pack')).data.fontCached, 'Legacy baseline can be imported in Studio');
      check(await page.locator('#legacy-font-tools').isVisible(), 'Original-font controls appear on 1.12');
      check(await page.locator('#pack-hint').textContent().then(x => x.includes('Unicode') && x.includes('8 pixels')), 'Legacy glyph size limitation is visible');
    } else check(await page.locator('#legacy-font-tools').isHidden(), 'Modern font generation needs no legacy baseline');
    await page.locator('#pack-build').click(); await success();
    const pack = (await api('display/pack')).data;
    check(pack.glyphs === 1 && !pack.error && pack.legacy === legacy, 'Pack includes the created glyph');
    const downloadEvent = page.waitForEvent('download'); await page.locator('#pack-download').click(); const download = await downloadEvent;
    const packPath = path.join(output, 'resource-pack.zip'); await download.saveAs(packPath);
    const zip = fs.readFileSync(packPath);
    check(zip[0] === 0x50 && zip[1] === 0x4b, 'Download is a real ZIP');
    check(legacy ? zip.includes(Buffer.from('glyph_sizes.bin')) && zip.includes(Buffer.from('unicode_page_e0.png')) && !zip.includes(Buffer.from('font/default.json')) : zip.includes(Buffer.from('font/default.json')), 'ZIP font layout matches the server version');
    await page.screenshot({ path: path.join(output, 'glyphs-desktop.png'), fullPage: true });
    await page.locator('#studio-image-upload').setInputFiles(path.join(project, '.build/test-gif.gif'));
    await page.waitForFunction(() => document.querySelectorAll('#glyph-images [data-image]').length === 2);
    const animated = (await api('display/assets')).data.find(a => a.id !== asset.id);
    check(animated.frames === 4, 'Screen upload preserves all GIF frames');
    const repeated = page.waitForResponse(r => r.url().endsWith('/api/display/image') && r.request().method() === 'POST');
    await page.locator('#studio-image-upload').setInputFiles(path.join(project, '.build/test-gif.gif'));
    await repeated;
    check((await api('display/assets')).data.length === 2, 'Repeated GIF upload reuses the same asset');
    await page.locator('#pack-build').click(); await success();
    check((await api('display/pack')).data.glyphs === 5, 'Generated pack reserves a persistent code for every GIF frame');
    await page.locator('[data-panel="dream"]').click();
    await page.locator('#dream-images [data-image="' + animated.id + '"]').dragTo(page.locator('[data-dream-index="3"]'));
    check((await state()).slots[3].kind === 'IMAGE' && (await state()).slots[3].image === animated.id, 'Animated image can be placed in TAB');
    await page.locator('#dream-images [data-image="' + asset.id + '"]').dragTo(page.locator('[data-dream-index="2"]'));
    check((await state()).slots[2].kind === 'IMAGE' && (await state()).slots[2].image === asset.id, 'Image palette adds an assigned image to TAB');
    await page.locator('[data-panel="hud"]').click();
    await page.locator('#hud-images [data-image="' + asset.id + '"]').dragTo(page.locator('[data-hud-anchor="SUBTITLE"]'));
    check((await state()).screen.some(s => s.kind === 'IMAGE' && s.image === asset.id && s.anchor === 'SUBTITLE'), 'Image palette adds an assigned image on screen');
    await page.locator('#apply').click(); await success();
    await page.reload(); await page.waitForFunction(() => window.TabPrefixStudio?.state.design?.screen?.some(s => s.kind === 'IMAGE'));
    check((await state()).slots[2].image === asset.id, 'Image references survive a page reload');
    await page.locator('[data-panel="hud"]').click();
    check(await page.locator('#hud-canvas-mode').isDisabled()===legacy,'Free-canvas capability is gated by the actual server version');
    if(!legacy){
      await page.locator('#hud-canvas-mode').check();
      await page.locator('#hud-palette [data-element="PING"]').dragTo(page.locator('#screen-free'),{targetPosition:{x:90,y:60}});
      let free=(await state()).screen.find(e=>e.anchor==='FREE_XY');
      check(!!free&&Number.isInteger(free.x)&&Number.isInteger(free.y),'Canvas drop stores real integer coordinates');
      await page.locator('#screen-x').fill('-70');await page.locator('#screen-y').fill('-80');await page.locator('#screen-height').fill('12');
      free=(await state()).screen.find(e=>e.anchor==='FREE_XY');check(free.x===-70&&free.y===-80&&free.height===12,'Each canvas block has independent X, Y and size');
      await page.locator('#screen-x').fill('512.5');check((await state()).screen.find(e=>e.anchor==='FREE_XY').x===-70,'Fractional coordinates do not enter the saved document');await page.locator('#screen-x').fill('-70');
      check(await page.locator('[data-hud-id="'+free.id+'"]').count()===1,'Free block is visible on the canvas');
      await page.waitForFunction(()=>Array.from(document.querySelectorAll('.native-hud-element')).some(n=>n.textContent.includes('42 ms')));check(await page.locator('[data-hud-id="'+free.id+'"]').textContent().then(t=>t.includes('42 ms')),'Canvas preview uses server-rendered player values');await page.screenshot({path:path.join(output,'canvas-desktop.png'),fullPage:true});
      await page.locator('[data-hud-id="'+free.id+'"]').dragTo(page.locator('#screen-free'),{targetPosition:{x:200,y:80}});
      check((await state()).screen.find(e=>e.id===free.id).x!==-70,'Placed blocks can be dragged to a new coordinate');
      await page.locator('[data-panel="scoreboard"]').click();await page.locator('#sidebar-mode').selectOption('HUD');await page.locator('#sidebar-x').fill('60');await page.locator('#sidebar-y').fill('-120');
      await page.waitForFunction(()=>document.querySelectorAll('#score-preview-lines em').length===0);
      check((await state()).sidebarMode==='HUD'&&(await state()).sidebarX===60&&(await state()).sidebarY===-120,'Scoreless panel has its own placement');
      await page.locator('#apply').click();await success();saved=(await api('display/design')).data.design;
      check(saved.screen.some(e=>e.anchor==='FREE_XY')&&saved.sidebarMode==='HUD','Native HUD persists through SQLite');
      for(let attempt=0;attempt<100;attempt++){const current=(await api('display/pack')).data;if(current.error)throw new Error(current.error);if(!current.building&&current.hudProfiles>0)break;await page.waitForTimeout(200);}
      const nativePack=(await api('display/pack')).data;check(nativePack.hudProfiles>0,'Saving native geometry generates a matching pack automatically: '+JSON.stringify({pack:nativePack,screenEnabled:saved.screenEnabled,sidebarEnabled:saved.sidebarEnabled}));
      const fractional=JSON.parse(JSON.stringify(saved));fractional.screen.find(e=>e.anchor==='FREE_XY').x=.5;
      check((await api('display/design',{design:fractional,revision:(await api('display/design')).data.revision})).code===400,'Server independently rejects fractional coordinates');
      await page.locator('#sidebar-mode').selectOption('NATIVE');await page.locator('#apply').click();await success();
    }
    await page.locator('#workbench-theme').click();await page.reload();await page.waitForFunction(()=>window.TabPrefixStudio?.state.design);
    check(await page.evaluate(()=>document.documentElement.dataset.theme)==='light','Theme choice survives a page reload');await page.locator('#workbench-theme').click();
    await page.locator('[data-panel="settings"]').click();
    await page.locator('#pref-screen').uncheck(); await page.locator('#save-settings').click(); await success();
    check(!(await api('preferences')).data.screen, 'Personal screen opt-out persists');
    await page.locator('[data-panel="scoreboard"]').click();
    check(await page.locator('#score-number-hint').textContent().then(x => x.includes(legacy ? 'Older clients' : 'blank number')), 'Score number capability is explained');
    const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
    const mobile = await mobileContext.newPage(); mobile.on('pageerror', e => errors.push(e.message)); mobile.on('dialog', d => d.accept());
    await mobile.goto(info.admin); await mobile.waitForFunction(() => window.TabPrefixStudio?.state.design);
    await mobile.locator('[data-panel="dream"]').click(); await mobile.locator('#dream-clear').tap();
    await mobile.locator('#dream-palette [data-element="PING"]').tap(); await mobile.locator('[data-dream-index="0"]').tap();
    check(await mobile.evaluate(() => window.TabPrefixStudio.state.design.slots[0].line.text.includes('{ping}')), 'Phone tap selects an element and its destination');
    await mobile.locator('[data-dream-index="0"]').scrollIntoViewIfNeeded();
    const from = await mobile.locator('[data-dream-index="0"]').boundingBox(), to = await mobile.locator('[data-dream-index="20"]').boundingBox(), cdp = await mobileContext.newCDPSession(mobile);
    const a = { x: from.x + from.width / 2, y: from.y + from.height / 2 }, b = { x: to.x + to.width / 2, y: to.y + to.height / 2 };
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [a] });
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [b] });
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    check(await mobile.evaluate(() => window.TabPrefixStudio.state.design.slots[20].line.text.includes('{ping}') && window.TabPrefixStudio.state.design.slots[0].kind === 'EMPTY'), 'Phone touch drag swaps cells');
    check(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Dream phone layout has no horizontal overflow');
    await mobile.screenshot({ path: path.join(output, 'dream-mobile.png'), fullPage: true });
    await mobile.locator('[data-panel="hud"]').click();
    check(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'HUD phone layout has no horizontal overflow');
    if(!legacy){
      await mobile.locator('[data-panel="settings"]').click();await mobile.locator('#pref-screen').check();await mobile.locator('#save-settings').click();await mobile.waitForFunction(()=>document.querySelector('#notice').classList.contains('success'));check((await api('preferences')).data.screen,'Phone re-enables its own screen preview');await mobile.locator('[data-panel="hud"]').click();
      await mobile.locator('#hud-canvas-mode').check();await mobile.locator('#hud-palette [data-element="CLOCK"]').tap();
      await mobile.locator('#screen-free').tap({position:{x:90,y:65}});
      check(await mobile.evaluate(()=>window.TabPrefixStudio.state.design.screen.some(e=>e.anchor==='FREE_XY'&&e.line.text.includes('{time}'))),'Phone tap places a block at free coordinates');
      await mobile.waitForFunction(()=>Array.from(document.querySelectorAll('.native-hud-element')).some(n=>n.textContent.includes('12:34')));await mobile.screenshot({path:path.join(output,'canvas-mobile.png'),fullPage:true});
    }
    await mobile.locator('[data-panel="glyphs"]').click();
    check(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Glyph phone layout has no horizontal overflow');
    await mobile.screenshot({ path: path.join(output, 'glyphs-mobile.png'), fullPage: true });
    await mobileContext.close();
    await page.locator('[data-panel="glyphs"]').click(); await page.locator('#glyph-prefix-group').fill('vip'); await page.locator('#glyph-prefix-link').click();
    await page.waitForURL('**/editor#*'); await page.waitForFunction(() => document.querySelector('#group').textContent === 'vip');
    check(await page.locator('#group').textContent() === 'vip', 'Prefix editor opens for the selected group');
    check(errors.length === 0, 'No JavaScript errors: ' + errors.join('; '));
    console.log('PASS: ' + checks + ' Dream browser checks (' + (legacy ? '1.12.2' : '1.21.11') + '): drag/touch, SQLite save, HUD, glyphs, real pack ZIP, permissions and mobile.');
  } finally {
    if (browser) await browser.close();
    server.stdin.end('\n');
    await new Promise(resolve => { server.once('exit', resolve); setTimeout(() => { server.kill(); resolve(); }, 3000).unref(); });
  }
})().catch(e => { console.error(e); process.exitCode = 1; });
