'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.TABPREFIX_PLAYWRIGHT_MODULE||'playwright');
const project=path.resolve(process.argv[2]||'.'),output=path.join(project,'.build/studio-checks');fs.mkdirSync(output,{recursive:true});
let checks=0;const check=(ok,name)=>{assert.ok(ok,name);checks++;};
(async()=>{
 const {spawn}=require('node:child_process');
 const provided=fs.readdirSync(path.join(project,'.build/deps/provided')).filter(n=>n.endsWith('.jar')).map(n=>path.join(project,'.build/deps/provided',n));
 const cp=[path.join(project,'.build/tests.jar'),path.join(project,'dist/TabPrefix.jar'),...provided].join(path.delimiter);
 const server=spawn(process.env.TABPREFIX_JAVA||'java',['-Xmx384m','-Djava.awt.headless=true','-Dsun.net.http.allowRestrictedHeaders=true','-cp',cp,'me.snowsun.tabprefix.test.DisplayIntegrationTest',project,'--serve'],{stdio:['pipe','pipe','inherit']});
 let browser;
 try{
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Studio fixture startup timeout')),20000);server.stdout.on('data',data=>{if(data.toString().includes('STUDIO_READY')){clearTimeout(timer);resolve();}});server.once('exit',code=>{clearTimeout(timer);reject(new Error('Studio fixture exited: '+code));});});
  const info=JSON.parse(fs.readFileSync(path.join(project,'.build/studio-test.json'),'utf8')),token=info.admin.split('#')[1],base=info.admin.split('/studio#')[0];
  browser=await chromium.launch({headless:true,executablePath:process.env.TABPREFIX_BROWSER_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
  const context=await browser.newContext({viewport:{width:1450,height:1050}}),page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('dialog',dialog=>dialog.accept());
  const api=async(route,body)=>{const response=body?await context.request.post(base+'/api/'+route,{headers:{Authorization:'Bearer '+token},data:body}):await context.request.get(base+'/api/'+route,{headers:{Authorization:'Bearer '+token}});return {code:response.status(),data:await response.json()};};
  const success=()=>page.waitForFunction(()=>document.querySelector('#notice').classList.contains('success'));
  await page.goto(info.admin);await page.waitForFunction(()=>document.querySelector('#owner').textContent==='SnowySun'&&document.querySelector('#session-state').textContent==='Connected');
  check(await page.locator('.template').count()===4,'Four visual templates including calm TAB');
  check(await page.locator('h1').textContent()==='Your server. Your style.','English studio localization');
  await page.locator('#language').click();check(await page.locator('h1').textContent()==='Ваш сервер. Ваш стиль.','Russian studio localization');await page.locator('#language').click();
  await page.screenshot({path:path.join(output,'overview-desktop.png'),fullPage:true});
  await page.locator('[data-preset="neon"]').click();await page.waitForFunction(()=>!document.querySelector('#panel-tab').hidden);
  check(await page.locator('#layout-enabled').isChecked(),'Neon template enables fixed layout');
  check(await page.locator('.tab-slot').count()===80,'80 selectable slots');
  check(!(await page.locator('#apply').isDisabled()),'Template creates reviewable unsaved changes');
  await page.locator('.palette [data-kind="TEXT"]').click();await page.locator('#block-text').fill('<gold>HELLO</gold>');
  await page.waitForFunction(()=>document.querySelector('#block-preview').textContent==='HELLO');
  await page.locator('#format-bold').click();check(await page.locator('#block-text').inputValue().then(s=>s.includes('<bold>')),'Visual bold control updates block formatting');await page.locator('#format-bold').click();
  await page.locator('#text-color').evaluate(el=>{el.value='#93efc4';el.dispatchEvent(new Event('input',{bubbles:true}));});check(await page.locator('#block-text').inputValue().then(s=>s.includes('#93efc4')),'Visual color picker updates block formatting');
  check(await page.locator('#block-preview span').first().evaluate(el=>getComputedStyle(el).color)!=='','Server-rendered formatted preview');
  await page.locator('.tab-slot[data-index="0"]').dragTo(page.locator('.tab-slot[data-index="1"]'));
  check(await page.locator('.tab-slot[data-index="1"]').getAttribute('data-kind')==='TEXT','Native drag swaps TAB cells');
  await page.locator('#undo').click();check(await page.locator('.tab-slot[data-index="0"]').getAttribute('data-kind')==='TEXT','Undo restores moved cell');
  await page.locator('#redo').click();check(await page.locator('.tab-slot[data-index="1"]').getAttribute('data-kind')==='TEXT','Redo restores drag operation');
  await page.locator('.tab-slot[data-index="1"]').click();await page.locator('#block-text').fill('<green>ABCDEFGHIJKLMN</green>');await page.locator('#animation').selectOption('SCROLL');
  await page.locator('#animation-width').fill('4');await page.locator('#animation-width').press('Tab');
  await page.waitForFunction(()=>document.querySelector('#block-preview').textContent.length===4);
  check(await page.locator('#block-preview').textContent().then(x=>x.length===4),'Scroll window reflected in server preview');
  await page.locator('#pause').click();check(await page.locator('#pause').textContent()==='Resume','Animation preview pause');await page.locator('#pause').click();
  await page.screenshot({path:path.join(output,'tab-desktop.png'),fullPage:true});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Desktop studio has no page overflow');
  await page.locator('[data-panel="scoreboard"]').click();await page.locator('.line-block[data-section="sidebar"][data-index="1"]').click();await page.locator('#animation').selectOption('FRAMES');
  await page.locator('#animation-frames').fill('<green>ONE</green>\n<red>TWO</red>');
  await page.locator('#animation-speed').fill('0.1');await page.locator('#animation-speed').press('Tab');
  check(await page.locator('#frames-field').isVisible(),'Frame editor visible for frame animation');
  await page.locator('.line-block[data-section="sidebar"][data-index="0"]').dragTo(page.locator('.line-block[data-section="sidebar"][data-index="2"]'));
  check(await page.locator('.line-block[data-section="sidebar"][data-index="0"] .line-content').textContent().then(s=>s.trim().length>0),'Native drag reorders sidebar lines');
  await page.locator('#apply').click();await success();
  const saved=await api('display/design');check(saved.code===200&&saved.data.design.layoutEnabled,'Browser applies real display document');
  check(saved.data.design.sidebar[0].animation==='FRAMES'&&saved.data.design.sidebar[0].frames.length===2,'Frame animation persisted through real API');
  const p0=await api('display/preview',{design:saved.data.design,tick:0}),p2=await api('display/preview',{design:saved.data.design,tick:2});
  check(JSON.stringify(p0.data.sidebar[0]).includes('ONE')&&JSON.stringify(p2.data.sidebar[0]).includes('TWO'),'Frame timing matches server ticks');
  await page.screenshot({path:path.join(output,'scoreboard-desktop.png'),fullPage:true});
  await page.locator('[data-panel="nametags"]').click();await page.locator('#name-suffix').fill(' <aqua>★</aqua>');
  await page.waitForFunction(()=>document.querySelector('#nametag-preview').textContent.includes('★'));check(await page.locator('#nametag-preview').textContent().then(x=>x.includes('[VIP]')),'Name tag combines group prefix, name and suffix');
  await page.locator('#apply').click();await success();await page.screenshot({path:path.join(output,'nametags-desktop.png'),fullPage:true});
  await page.locator('[data-panel="bossbars"]').click();
  while(await page.locator('.boss-block').count()){await page.locator('.boss-block').first().click();await page.locator('#delete-block').click();}
  check(await page.locator('#boss-empty').isVisible(),'Clear starting state for boss-bar builder');
  await page.locator('#add-boss').click();await page.locator('#block-text').fill('<gold>{player} · {progress}%</gold>');
  check(await page.locator('#bossbars-enabled').isChecked(),'Adding a bar enables server boss bars');
  check(await page.locator('[data-bar-color]').count()===7&&await page.locator('#boss-style option').count()===5,'All native colors and styles exposed');
  await page.locator('[data-bar-color="GREEN"]').click();await page.locator('#boss-style').selectOption('SEGMENTED_10');
  await page.locator('#boss-progress-slider').evaluate(el=>{el.value='33.3';el.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.waitForFunction(()=>document.querySelector('#boss-preview-stack').textContent.includes('33.3%'));
  check(await page.locator('#boss-progress').inputValue()==='33.3','Fill slider and numeric field stay in sync');
  check(await page.locator('#boss-preview-stack .boss-track').first().getAttribute('aria-valuenow')==='33.3','Real API preview displays fractional fill');
  await page.locator('#animation').selectOption('FRAMES');await page.locator('#animation-frames').fill('<gold>FIRST {player}</gold>\n<aqua>SECOND {progress}%</aqua>');
  await page.locator('#animation-speed').fill('0.1');await page.locator('#animation-speed').press('Tab');
  await page.locator('[data-boss-preset="health"]').click();check(await page.locator('#boss-progress-mode').inputValue()==='HEALTH','Health preset creates an editable dynamic bar');
  await page.locator('#boss-progress-mode').selectOption('CUSTOM');await page.locator('#boss-progress-source').selectOption('level');await page.locator('#boss-progress-max').fill('10');await page.locator('#boss-progress-max').press('Tab');
  await page.waitForFunction(()=>document.querySelectorAll('#boss-preview-stack .boss-track')[1]?.getAttribute('aria-valuenow')==='50');
  check(await page.locator('#boss-custom-fields').isVisible(),'Custom fill uses a placeholder and full-bar value');
  await page.locator('[data-boss-preset="timer"]').click();await page.locator('#boss-duration').fill('2');await page.locator('#boss-duration').press('Tab');await page.locator('#boss-loop').uncheck();
  check(await page.locator('#boss-hide-after-field').isVisible(),'Finite timer exposes hide-on-completion');
  await page.locator('#boss-fields details').first().locator('summary').click();await page.locator('#boss-worlds').fill('world_nether');
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('.boss-meta')).some(el=>el.textContent.includes('Different world')));
  check(await page.locator('#boss-preview-stack .boss-graphic').count()===2,'World filter affects real server preview');
  await page.locator('#boss-worlds').fill('world');await page.locator('#boss-permission').fill('example.vip');
  await page.locator('#boss-fields details').nth(1).locator('summary').click();await page.locator('#boss-darken-sky').check();await page.locator('#boss-play-music').check();await page.locator('#boss-create-fog').check();
  await page.locator('.boss-block[data-index="0"]').dragTo(page.locator('.boss-block[data-index="2"]'));
  check(await page.locator('#animation').inputValue()==='FRAMES','Native drag moves the whole bar with its title animation');
  await page.locator('#undo').click();check(await page.locator('.boss-block[data-index="0"]').getAttribute('class').then(s=>!s.includes('selected')),'Undo restores bar ordering');await page.locator('#redo').click();
  await page.locator('.boss-block[data-index="2"]').click();await page.locator('#duplicate-boss').click();check(await page.locator('.boss-block').count()===4,'Duplicate preserves editable bar settings');await page.locator('#delete-block').click();
  await page.locator('#boss-mode').selectOption('ROTATE');await page.locator('#boss-rotate-seconds').fill('1');await page.locator('#boss-rotate-seconds').press('Tab');
  check(await page.locator('#boss-rotate-field').isVisible(),'Rotation exposes seconds-based interval');
  await page.locator('#apply').click();await success();const bossSaved=await api('display/design'),bossDoc=bossSaved.data.design;
  check(bossDoc.bossBars.length===3&&bossDoc.bossBarMode==='ROTATE'&&bossDoc.bossBarRotateTicks===20,'Boss order and rotation persist through real API');
  check(bossDoc.bossBars[2].color==='GREEN'&&bossDoc.bossBars[2].style==='SEGMENTED_10'&&bossDoc.bossBars[2].progress===33.3,'Native appearance and fractional fill persisted');
  check(bossDoc.bossBars[1].durationTicks===40&&!bossDoc.bossBars[1].loop&&bossDoc.bossBars[1].darkenSky&&bossDoc.bossBars[1].playMusic&&bossDoc.bossBars[1].createFog&&bossDoc.bossBars[1].permission==='example.vip','Timer, filters and native effects persisted');
  const boss0=await api('display/preview',{design:bossDoc,tick:0}),boss20=await api('display/preview',{design:bossDoc,tick:20}),boss40=await api('display/preview',{design:bossDoc,tick:40});
  check(boss0.data.bossBars[0].active&&boss20.data.bossBars[1].active&&boss40.data.bossBars[2].active,'Rotation uses deterministic server timing');
  check(boss0.data.bossBars[1].progress===1&&boss20.data.bossBars[1].progress===.5&&boss40.data.bossBars[1].progress===0,'Countdown preview matches configured duration');
  check(JSON.stringify(boss0.data.bossBars[2].title).includes('FIRST')&&JSON.stringify((await api('display/preview',{design:bossDoc,tick:2})).data.bossBars[2].title).includes('SECOND'),'Boss title frame animation uses real renderer');
  await page.locator('#boss-mode').selectOption('STACKED');await page.locator('.boss-block[data-index="1"]').click();await page.waitForFunction(()=>document.querySelectorAll('#boss-preview-stack .boss-graphic').length===3);
  await page.screenshot({path:path.join(output,'bossbars-desktop.png'),fullPage:true});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Boss builder desktop has no horizontal overflow');
  await page.locator('#apply').click();await success();
  await page.locator('[data-panel="overview"]').click();await page.locator('[data-preset="calm"]').click();await page.waitForFunction(()=>document.querySelectorAll('.group-block').length===4);
  check(await page.locator('#tab-format-enabled').isChecked()&&await page.locator('#native-sort-enabled').isChecked()&&!(await page.locator('#layout-enabled').isChecked()),'Calm preset formats and sorts the ordinary TAB');
  check(await page.locator('#sort').inputValue()==='PRIORITY','Calm preset uses draggable group priority');
  check(await page.locator('.group-block').first().textContent().then(s=>s.includes('owner')),'LuckPerms groups imported by actual cached weight');
  await page.locator('.group-block[data-index="2"]').click();check(await page.locator('#role-group').inputValue()==='vip','Selecting a group opens its suffix editor');
  await page.locator('#role-name-color').evaluate(el=>{el.value='#85b5ff';el.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.locator('#block-text').fill('<gold>★ {group}</gold>');await page.waitForFunction(()=>document.querySelector('.group-block[data-index="2"] .group-suffix').textContent.includes('★ vip'));
  check(await page.locator('#block-preview').textContent().then(s=>s.includes('★ vip')),'Group suffix preview uses server placeholders');
  await page.locator('#role-suffix-mode').selectOption('LUCKPERMS');check(await page.locator('#block-text').isDisabled(),'LuckPerms suffix source disables custom-text controls');
  await page.waitForFunction(()=>document.querySelector('#block-preview').textContent.trim()==='LP');check(await page.locator('#block-preview').textContent().then(s=>s.trim()==='LP'),'Cached LuckPerms suffix preview');
  await page.locator('#role-suffix-mode').selectOption('NONE');await page.waitForFunction(()=>document.querySelector('#block-preview').textContent==='');check(await page.locator('#block-text').isDisabled(),'Hidden suffix preserves its custom draft');
  await page.locator('#role-suffix-mode').selectOption('CUSTOM');await page.locator('#animation').selectOption('FRAMES');await page.locator('#animation-frames').fill('<gold>STAR {group}</gold>\n<aqua>MOON {group}</aqua>');await page.locator('#animation-speed').fill('0.1');await page.locator('#animation-speed').press('Tab');
  await page.locator('.group-block[data-index="2"]').dragTo(page.locator('.group-block[data-index="0"]'));check(await page.locator('.group-block').first().textContent().then(s=>s.includes('vip')),'Native drag changes group priority');
  await page.locator('#undo').click();check(await page.locator('.group-block').first().textContent().then(s=>s.includes('owner')),'Undo restores group priority');await page.locator('#redo').click();
  await page.locator('#import-luck-groups').click();check(await page.locator('.group-block').count()===4,'Importing existing LuckPerms groups does not duplicate styles');
  await page.locator('#add-group-style').click();await page.locator('#role-group').fill('staff');await page.locator('#role-group').press('Tab');await page.locator('[data-suffix-snippet="world"]').click();check(await page.locator('#block-text').inputValue()==='<gray>· {world}</gray>','One-click world suffix remains fully editable');
  await page.locator('#role-group').fill('vip');await page.locator('#role-group').press('Tab');check(await page.locator('#notice').textContent().then(s=>s.includes('already')),'Duplicate group refused without losing the draft');await page.locator('#delete-block').click();
  await page.locator('#edit-player-format').click();check(await page.locator('#move-up').isHidden()&&await page.locator('#delete-block').isHidden(),'Global player format has no misleading move or delete actions');
  await page.locator('#block-text').fill('{prefix}{display_name}{suffix} <dark_gray>·</dark_gray> <gray>{ping} ms</gray>');await page.waitForFunction(()=>document.querySelector('#player-format-preview').textContent.includes('42 ms'));
  check(await page.locator('#tab-preview-slots').textContent().then(s=>s.includes('42 ms')),'Ordinary player list preview uses the custom format');
  for(const mode of ['NAME','GROUP','WEIGHT','PING','WORLD','PRIORITY'])await page.locator('#sort').selectOption(mode);
  await page.locator('#sort-reverse').check();await page.locator('#apply').click();await success();const tabSaved=(await api('display/design')).data.design;
  check(tabSaved.groupStyles[0].group==='vip'&&tabSaved.groupStyles[0].nameColor==='#85b5ff'&&tabSaved.groupStyles[0].suffix.frames.length===2,'Group priority, color and suffix frames saved through real API');
  check(tabSaved.sort==='PRIORITY'&&tabSaved.sortReverse&&tabSaved.tabPlayerFormat.text.includes('{ping}'),'All custom TAB settings saved');
  check(tabSaved.bossBars.length===3&&tabSaved.bossBars[2].progress===33.3,'Calm TAB preset preserves existing boss bars');
  const tab0=await api('display/preview',{design:tabSaved,tick:0}),tab2=await api('display/preview',{design:tabSaved,tick:2});check(JSON.stringify(tab0.data.playerFormat).includes('STAR vip')&&JSON.stringify(tab2.data.playerFormat).includes('MOON vip'),'Suffix frame timing is reflected in the ordinary TAB format');
  await page.screenshot({path:path.join(output,'tab-format-desktop.png'),fullPage:true});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Group and format builder has no desktop overflow');
  await page.locator('[data-panel="settings"]').click();await page.locator('#pref-layout').uncheck();await page.locator('#pref-animations').uncheck();await page.locator('#pref-bossBars').uncheck();await page.locator('#save-settings').click();await success();
  const pref=await api('preferences');check(!pref.data.layout&&!pref.data.animations,'Personal toggles saved for owner');
  check(!pref.data.bossBars,'Personal boss-bar opt-out saved');
  await page.locator('#pref-suffixes').uncheck();await page.locator('#pref-sorting').uncheck();await page.locator('#save-settings').click();await success();const tabPrefs=await api('preferences');check(!tabPrefs.data.suffixes&&!tabPrefs.data.sorting,'Personal suffix and sorting opt-out saved');
  await page.locator('#pref-suffixes').check();await page.locator('#pref-sorting').check();await page.locator('#save-settings').click();await success();
  const player=await context.newPage();player.on('pageerror',e=>errors.push(e.message));await player.goto(info.player);await player.waitForFunction(()=>!document.querySelector('#panel-settings').hidden);
  check(await player.locator('.nav:visible').count()===1&&await player.locator('#design-actions').isHidden(),'Player-only session exposes only personal settings');
  check(await player.locator('#pref-layout').isChecked(),'Another player keeps their own settings');check(await player.locator('#pref-bossBars').isChecked(),'Another player keeps boss bars enabled');check(await player.locator('#pref-suffixes').isChecked()&&await player.locator('#pref-sorting').isChecked(),'Another player keeps suffixes and sorting enabled');await player.close();
  await page.locator('[data-panel="overview"]').click();await page.locator('#server-name').fill('Browser draft');
  const other=await api('display/design');other.data.design.serverName='Competing admin';check((await api('display/design',other.data)).code===200,'Competing administrator commits a new revision');
  await page.locator('#apply').click();await page.waitForFunction(()=>document.querySelector('#notice').classList.contains('error'));
  check(await page.locator('#notice').textContent().then(x=>x.includes('Another administrator')),'Revision conflict is visible and preserves browser draft');
  check(await page.locator('#server-name').inputValue()==='Browser draft','Conflict retains unsaved work');
  await page.locator('#reload').click();await page.waitForFunction(()=>document.querySelector('#server-name').value==='Competing admin');
  const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;const exportPath=path.join(output,'export.json');await download.saveAs(exportPath);
  const exported=JSON.parse(fs.readFileSync(exportPath,'utf8'));check(exported.schema===1&&exported.slots.length===80,'Valid reusable JSON export');exported.serverName='Imported template';fs.writeFileSync(exportPath,JSON.stringify(exported));
  check(exported.bossBars.length===3,'JSON export includes full boss-bar document');
  check(exported.groupStyles[0].group==='vip'&&exported.tabPlayerFormat.text.includes('{suffix}'),'JSON export includes suffixes, priorities and player format');
  exported.slots[1]={kind:'TEXT',playerIndex:1,line:{text:'<gold>MOBILE</gold>',animation:'NONE',speed:6,width:28,gap:5,frames:[]}};fs.writeFileSync(exportPath,JSON.stringify(exported));
  await page.locator('#import-file').setInputFiles(exportPath);await page.waitForFunction(()=>document.querySelector('#server-name').value==='Imported template');check(!(await page.locator('#apply').isDisabled()),'Validated import remains a draft until apply');
  const oldTemplate=JSON.parse(JSON.stringify(exported));for(const key of ['bossBars','bossBarsEnabled','bossBarMode','bossBarRotateTicks','groupStyles','tabPlayerFormat','tabFormatEnabled','nativeSortEnabled','sortReverse','suffixEnabled','luckSuffixFallback'])delete oldTemplate[key];oldTemplate.serverName='Older 2.1 template';fs.writeFileSync(exportPath,JSON.stringify(oldTemplate));
  await page.locator('#import-file').setInputFiles(exportPath);await page.waitForFunction(()=>document.querySelector('#server-name').value==='Older 2.1 template');await page.locator('[data-panel="bossbars"]').click();check(await page.locator('#boss-empty').isVisible(),'Older 2.1 template imports without boss fields');
  const minimalTemplate=JSON.parse(JSON.stringify(exported));minimalTemplate.bossBars=[{id:'minimal-import',line:{text:'<aqua>MINIMAL {player}</aqua>'}}];fs.writeFileSync(exportPath,JSON.stringify(minimalTemplate));
  await page.locator('#import-file').setInputFiles(exportPath);await page.waitForFunction(()=>document.querySelectorAll('.boss-block').length===1);await page.locator('.boss-block').click();check(await page.locator('#boss-color').inputValue()==='PURPLE'&&await page.locator('#boss-progress').inputValue()==='100','Minimal validated boss template receives editable default settings');
  fs.writeFileSync(exportPath,JSON.stringify(exported));await page.locator('#import-file').setInputFiles(exportPath);await page.waitForFunction(()=>document.querySelectorAll('.boss-block').length===3);
  await page.locator('#apply').click();await success();
  const mobileContext=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),mobile=await mobileContext.newPage();mobile.on('pageerror',e=>errors.push(e.message));
  await mobile.goto(info.admin);await mobile.waitForFunction(()=>document.querySelector('#owner').textContent==='SnowySun'&&document.querySelector('#session-state').textContent==='Connected');await mobile.locator('[data-panel="tab"]').click();await mobile.locator('.tab-slot[data-index="1"]').click();
  check(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile studio has no page overflow');
  await mobile.locator('#move-down').click();check(await mobile.locator('.tab-slot[data-index="2"]').getAttribute('data-kind')==='TEXT','Mobile move buttons rearrange cells');
  await mobile.locator('.tab-slot[data-index="2"] .grab').scrollIntoViewIfNeeded();const start=await mobile.locator('.tab-slot[data-index="2"] .grab').boundingBox(),end=await mobile.locator('.tab-slot[data-index="3"] .grab').boundingBox();
  const cdp=await mobileContext.newCDPSession(mobile);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:start.x+start.width/2,y:start.y+start.height/2}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:end.x+end.width/2,y:end.y+end.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  check(await mobile.locator('.tab-slot[data-index="3"]').getAttribute('data-kind')==='TEXT','Real touch drag rearranges TAB cells');
  await mobile.screenshot({path:path.join(output,'tab-mobile.png'),fullPage:true});
  await mobile.locator('.group-block[data-index="0"] .grab').scrollIntoViewIfNeeded();const groupStart=await mobile.locator('.group-block[data-index="0"] .grab').boundingBox(),groupEnd=await mobile.locator('.group-block[data-index="1"] .grab').boundingBox();
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:groupStart.x+groupStart.width/2,y:groupStart.y+groupStart.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:groupEnd.x+groupEnd.width/2,y:groupEnd.y+groupEnd.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  check(await mobile.locator('#role-group').inputValue()==='vip'&&await mobile.locator('.group-block[data-index="1"]').textContent().then(s=>s.includes('vip')),'Real touch drag reorders group priority with its settings');
  await mobile.waitForFunction(()=>document.querySelector('#block-preview').textContent.includes('STAR vip')&&document.querySelector('#player-format-preview').textContent.includes('SnowySun'));
  check(await mobile.locator('#tab-preview-slots').textContent().then(s=>s.includes('STAR vip')),'Mobile ordinary TAB renders the suffix while personal animation is paused');
  check(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Group suffix editor has no mobile overflow');await mobile.screenshot({path:path.join(output,'tab-format-mobile.png'),fullPage:true});
  await mobile.locator('[data-panel="bossbars"]').click();await mobile.locator('.boss-block[data-index="0"] .grab').scrollIntoViewIfNeeded();
  const bossStart=await mobile.locator('.boss-block[data-index="0"] .grab').boundingBox(),bossEnd=await mobile.locator('.boss-block[data-index="1"] .grab').boundingBox();
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:bossStart.x+bossStart.width/2,y:bossStart.y+bossStart.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:bossEnd.x+bossEnd.width/2,y:bossEnd.y+bossEnd.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  check(await mobile.locator('#boss-progress-mode').inputValue()==='CUSTOM','Real touch drag moves a whole boss bar');
  await mobile.waitForFunction(()=>document.querySelector('#block-preview').textContent.includes('SnowySun')&&Array.from(document.querySelectorAll('.boss-meta')).some(el=>el.textContent.includes('personal settings')));
  check(await mobile.locator('#boss-preview-empty').isVisible(),'Mobile preview respects saved personal boss-bar opt-out');
  check(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Boss builder mobile has no horizontal overflow');
  await mobile.screenshot({path:path.join(output,'bossbars-mobile.png'),fullPage:true});await mobileContext.close();
  const noToken=await context.newPage();await noToken.goto(base+'/studio');check(await noToken.locator('#design-actions').isHidden()&&await noToken.locator('.nav').first().isDisabled(),'Studio without token is disabled');await noToken.close();
  const prefixes=await context.newPage();await prefixes.goto(info.prefix);await prefixes.waitForFunction(()=>document.querySelector('#group').textContent==='vip');
  check(await prefixes.locator('#studio-link').isVisible(),'Prefix editor links to display studio for permitted sessions');await prefixes.close();
  await page.route('**/api/session',async route=>{const response=await route.fetch(),body=await response.json();Object.assign(body,{language:'ru',minecraftVersion:'1.12.2',bitmapFontsSupported:false,rgbSupported:false,teamTextLimit:16});await route.fulfill({response,json:body});});
  await page.reload();await page.locator('#compatibility-hint').waitFor({state:'visible'});
  check(await page.locator('#compatibility-hint').textContent().then(x=>x.includes('1.12.2')&&x.includes('Unicode')),'Legacy Studio explains server limitations');
  await page.locator('#language').click();check(await page.locator('#compatibility-hint').textContent().then(x=>x.includes('standard colors')),'Studio compatibility hint follows language switch');
  check(errors.length===0,'No JavaScript errors: '+errors.join('; '));
  console.log('PASS: '+checks+' studio browser checks: real HTTP, presets, desktop and touch drag, undo/redo, animations, apply/conflicts, import/export, permissions and mobile.');
 }finally{
  if(browser)await browser.close();server.stdin.end('\n');await new Promise(resolve=>{server.once('exit',resolve);setTimeout(()=>{server.kill();resolve();},3000).unref();});
 }
})().catch(e=>{console.error(e);process.exitCode=1;});
