'use strict';
(() => {
 const $=id=>document.getElementById(id), paths={search:'M21 21l-5-5 M18 10a8 8 0 1 0-16 0a8 8 0 0 0 16 0',sun:'M12 8a4 4 0 1 0 0 8a4 4 0 0 0 0-8 M12 2v2 M12 20v2 M2 12h2 M20 12h2 M5 5l1.5 1.5 M17.5 17.5L19 19 M5 19l1.5-1.5 M17.5 6.5L19 5',moon:'M20.5 13A9 9 0 0 1 11 3.5a9 9 0 1 0 9.5 9.5',TEXT:'M4 5h16 M12 5v15 M8 20h8',PLAYER:'M12 12a4 4 0 1 0 0-8a4 4 0 0 0 0 8 M4 21v-2a8 8 0 0 1 16 0v2',PLAYERS:'M8 11a3 3 0 1 0 0-6a3 3 0 0 0 0 6 M2 20v-2a6 6 0 0 1 12 0v2 M16 5a3 3 0 0 1 0 6 M16 14a6 6 0 0 1 6 6',ONLINE:'M4 16v4 M9 12v8 M14 8v12 M19 4v16',HEALTH:'M20 5a5 5 0 0 0-8 1a5 5 0 0 0-8-1c-4 4 1 9 8 15c7-6 12-11 8-15',PING:'M3 9a14 14 0 0 1 18 0 M6 13a9 9 0 0 1 12 0 M9 17a4 4 0 0 1 6 0 M12 21h.01',WORLD:'M12 2a10 10 0 1 0 0 20a10 10 0 0 0 0-20 M2 12h20 M12 2c-6 5-6 15 0 20c6-5 6-15 0-20',CLOCK:'M12 2a10 10 0 1 0 0 20a10 10 0 0 0 0-20 M12 6v6l4 2',SEPARATOR:'M3 12h18',EMPTY:'M12 4v16 M4 12h16',IMAGE:'M3 3h18v18H3z M3 17l6-6 4 4 3-3 5 5 M16 7h.01',save:'M5 3h12l4 4v14H3V3z M7 3v6h10V3 M7 21v-8h10v8'};
 function icon(key){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),p=document.createElementNS(svg.namespaceURI,'path');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.classList.add('wb-icon');p.setAttribute('d',paths[key]||paths.TEXT);svg.append(p);return svg;}
 document.querySelector('.brand')?.addEventListener('click',e=>{e.preventDefault();const home=document.querySelector('.nav[data-panel="overview"]');if(home)home.click();else window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
 const language=()=>document.documentElement.lang==='ru',say=(ru,en)=>language()?ru:en;
 const tools=document.createElement('div');tools.className='wb-tools';const theme=document.createElement('button'),search=document.createElement('button');theme.id='workbench-theme';search.id='workbench-search';for(const button of[search,theme]){button.type='button';button.className='wb-tool';tools.append(button);}
 (document.querySelector('.top-actions')||document.querySelector('.page-actions')||document.querySelector('.topbar')||document.querySelector('.sidebar')).append(tools);
 function applyTheme(value){document.documentElement.dataset.theme=value;theme.replaceChildren(icon(value==='light'?'moon':'sun'));theme.title=say('Сменить тему','Change theme');theme.setAttribute('aria-label',theme.title);theme.setAttribute('aria-pressed',String(value==='light'));}
 let chosen='dark';try{chosen=localStorage.getItem('tabprefix-theme')||chosen;}catch(_){}applyTheme(chosen==='light'?'light':'dark');theme.onclick=()=>{const next=document.documentElement.dataset.theme==='light'?'dark':'light';applyTheme(next);try{localStorage.setItem('tabprefix-theme',next);}catch(_){}};
 search.append(icon('search'));const key=document.createElement('span');key.className='wb-key';key.textContent='⌘ K';search.append(key);search.title=say('Найти настройку · Ctrl K','Find a setting · Ctrl K');search.setAttribute('aria-label',search.title);
 const dialog=document.createElement('dialog');dialog.className='wb-dialog';dialog.id='workbench-command';const head=document.createElement('div');head.className='wb-search-head';const query=document.createElement('input');query.id='workbench-query';query.type='search';query.autocomplete='off';const close=document.createElement('button');close.type='button';close.textContent='Esc';head.append(icon('search'),query,close);const results=document.createElement('div');results.className='wb-results';dialog.append(head,results);document.body.append(dialog);close.onclick=()=>dialog.close();
 function commands(){const nav=Array.from(document.querySelectorAll('.nav[data-panel]')).filter(n=>!n.hidden);if(nav.length)return nav.map(n=>({label:n.textContent.trim(),action:()=>n.click(),icon:n.dataset.panel==='glyphs'?'IMAGE':n.dataset.panel==='settings'?'search':'TEXT'}));return [['image-card','Изображение и анимация','Image & animation','IMAGE'],['text-card','Текстовый префикс','Text prefix','TEXT'],['preview-card','Предпросмотр','Live preview','PLAYER'],['save-card','Сохранение','Save prefix','save']].map(([selector,ru,en,image])=>({label:say(ru,en),icon:image,action:()=>document.querySelector('.'+selector)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}));}
 function filter(){results.replaceChildren();for(const item of commands().filter(n=>n.label.toLowerCase().includes(query.value.trim().toLowerCase()))){const button=document.createElement('button');button.type='button';button.className='wb-command';button.append(icon(item.icon),document.createTextNode(item.label));button.onclick=()=>{dialog.close();item.action();};results.append(button);}if(!results.childElementCount){const empty=document.createElement('p');empty.className='wb-empty';empty.textContent=say('Ничего не найдено','No matching settings');results.append(empty);}}
 function open(){query.placeholder=say('Куда перейти?','Where would you like to go?');query.setAttribute('aria-label',query.placeholder);query.value='';filter();dialog.showModal();query.focus();}search.onclick=open;query.oninput=filter;query.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();dialog.close();return;}if(e.key==='Enter'){e.preventDefault();results.querySelector('button')?.click();}if(e.key==='ArrowDown'){e.preventDefault();results.querySelector('button')?.focus();}};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(dialog.open)dialog.close();else open();}});dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}};
 function decorate(){document.querySelectorAll('.element-tile').forEach(n=>{const mark=n.querySelector('.tile-icon');if(mark&&!mark.querySelector('svg'))mark.replaceChildren(icon(n.dataset.element||'TEXT'));});}
 window.TabPrefixWorkbench={icon,decorate};window.addEventListener('studio-change',decorate);window.addEventListener('studio-preview',decorate);decorate();
 if($('text')){const presets=document.createElement('div');presets.className='wb-presets';for(const[label,value]of[['VIP','<gradient:#f4d17a:#f6a35e>[VIP]</gradient> '],['ADMIN','<gradient:#ff8598:#ffbf85>[ADMIN]</gradient> '],['HELPER','<gradient:#65e5bd:#80bfff>[HELPER]</gradient> ']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>{$('text-format').value='MINIMESSAGE';$('text-override').checked=true;$('text-override').dispatchEvent(new Event('change'));$('text').value=value;$('text').dispatchEvent(new Event('input'));};presets.append(b);}document.querySelector('.text-fields').after(presets);}
})();
